apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-server
  labels:
    app: argocd
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /argo
        backend:
          serviceName: argocd-server
          servicePort: 2746
